/**
 * Lista padronizada de funções de colaboradores.
 * Todas as variações devem ser normalizadas para uma destas.
 */
export const JOB_FUNCTIONS = [
  'ALMOXARIFE',
  'ANALISTA DE PLANEJAMENTO',
  'CALDEIREIRO CONVENCIONAL',
  'CALDEIREIRO ESCALADOR N1',
  'CALDEIREIRO ESCALADOR N2',
  'CALDEIREIRO ESCALADOR N3',
  'COMERCIAL',
  'COORDENADOR',
  'DESENVOLVEDOR',
  'DIRETOR',
  'ELETRICISTA ESCALADOR N1',
  'GERENTE',
  'INSPETOR',
  'INSPETOR DE PINTURA',
  'INSPETOR DE SOLDA',
  'MARKETING',
  'MECÂNICO CONVENCIONAL',
  'MECÂNICO ESCALADOR N1',
  'MECÂNICO ESCALADOR N2',
  'MECÂNICO ESCALADOR N3',
  'MEIO OFICIAL',
  'MOTORISTA',
  'PINTOR CONVENCIONAL',
  'PINTOR ESCALADOR N1',
  'PINTOR ESCALADOR N2',
  'PINTOR ESCALADOR N3',
  'PROGRAMADOR',
  'PROJETISTA',
  'RH',
  'SERVIÇOS GERAIS',
  'SOLDADOR CONVENCIONAL',
  'SOLDADOR ESCALADOR N1',
  'SOLDADOR ESCALADOR N2',
  'SOLDADOR ESCALADOR N3',
  'SUPERVISOR DE OBRA',
  'SUPERVISOR DE SEGURANÇA',
  'SUPERVISOR ESCALADOR N3',
  'SUPERVISOR JUNIOR',
  'TÉCNICO EM SEGURANÇA DO TRABALHO',
  'TI',
] as const;

export type JobFunction = (typeof JOB_FUNCTIONS)[number];

/**
 * Mapa de sinônimos → função padronizada.
 * Chaves devem ser UPPERCASE e sem acentos extras.
 */
const SYNONYMS: Record<string, string> = {
  // Mecânico
  'MECANICO': 'MECÂNICO CONVENCIONAL',
  'MECÂNICO': 'MECÂNICO CONVENCIONAL',
  'MECANICO CONVENCIONAL': 'MECÂNICO CONVENCIONAL',
  'MECANICO N1': 'MECÂNICO ESCALADOR N1',
  'MECÂNICO N1': 'MECÂNICO ESCALADOR N1',
  'MECANICO ESCALADOR': 'MECÂNICO ESCALADOR N1',
  'MECÂNICO ESCALADOR': 'MECÂNICO ESCALADOR N1',
  'MECANICO ESCALADOR N1': 'MECÂNICO ESCALADOR N1',
  'MECÂNICO ESCALADOR N1': 'MECÂNICO ESCALADOR N1',
  'MECANICO N2': 'MECÂNICO ESCALADOR N2',
  'MECÂNICO N2': 'MECÂNICO ESCALADOR N2',
  'MECANICO ESCALADOR N2': 'MECÂNICO ESCALADOR N2',
  'MECÂNICO ESCALADOR N2': 'MECÂNICO ESCALADOR N2',
  'MECANICO N3': 'MECÂNICO ESCALADOR N3',
  'MECÂNICO N3': 'MECÂNICO ESCALADOR N3',
  'MECANICO ESCALADOR N3': 'MECÂNICO ESCALADOR N3',
  'MECÂNICO ESCALADOR N3': 'MECÂNICO ESCALADOR N3',
  'MEC': 'MECÂNICO CONVENCIONAL',
  'MEC.': 'MECÂNICO CONVENCIONAL',

  // Soldador
  'SOLDADOR': 'SOLDADOR CONVENCIONAL',
  'SOLD': 'SOLDADOR CONVENCIONAL',
  'SOLD.': 'SOLDADOR CONVENCIONAL',
  'SOLDADOR ESCALADOR': 'SOLDADOR ESCALADOR N1',
  'SOLDADOR N1': 'SOLDADOR ESCALADOR N1',
  'SOLDADOR ESCALADOR N1': 'SOLDADOR ESCALADOR N1',
  'SOLDADOR N2': 'SOLDADOR ESCALADOR N2',
  'SOLDADOR ESCALADOR N2': 'SOLDADOR ESCALADOR N2',
  'SOLDADOR N3': 'SOLDADOR ESCALADOR N3',
  'SOLDADOR ESCALADOR N3': 'SOLDADOR ESCALADOR N3',

  // Caldeireiro
  'CALDEIREIRO': 'CALDEIREIRO CONVENCIONAL',
  'CALD': 'CALDEIREIRO CONVENCIONAL',
  'CALD.': 'CALDEIREIRO CONVENCIONAL',
  'CALDEIREIRO ESCALADOR': 'CALDEIREIRO ESCALADOR N1',
  'CALDEIREIRO N1': 'CALDEIREIRO ESCALADOR N1',
  'CALDEIREIRO ESCALADOR N1': 'CALDEIREIRO ESCALADOR N1',
  'CALDEIREIRO N2': 'CALDEIREIRO ESCALADOR N2',
  'CALDEIREIRO ESCALADOR N2': 'CALDEIREIRO ESCALADOR N2',
  'CALDEIREIRO N3': 'CALDEIREIRO ESCALADOR N3',
  'CALDEIREIRO ESCALADOR N3': 'CALDEIREIRO ESCALADOR N3',

  // Pintor
  'PINTOR': 'PINTOR CONVENCIONAL',
  'PINTOR ESCALADOR': 'PINTOR ESCALADOR N1',
  'PINTOR N1': 'PINTOR ESCALADOR N1',
  'PINTOR ESCALADOR N1': 'PINTOR ESCALADOR N1',
  'PINTOR N2': 'PINTOR ESCALADOR N2',
  'PINTOR ESCALADOR N2': 'PINTOR ESCALADOR N2',
  'PINTOR N3': 'PINTOR ESCALADOR N3',
  'PINTOR ESCALADOR N3': 'PINTOR ESCALADOR N3',

  // Outros
  'MEIO OFICIAL': 'MEIO OFICIAL',
  'PROGRAMADOR': 'PROGRAMADOR',
  'PROJETISTA': 'PROJETISTA',
  'SUPERVISOR N3': 'SUPERVISOR ESCALADOR N3',
  'SUPERVISOR ESCALADOR N3': 'SUPERVISOR ESCALADOR N3',
  'SUP N3': 'SUPERVISOR ESCALADOR N3',
  'SUP. N3': 'SUPERVISOR ESCALADOR N3',
  'SUPERVISOR': 'SUPERVISOR ESCALADOR N3',
  'SUPERVISOR ALPINISTA N3': 'SUPERVISOR ESCALADOR N3',
  'SUPERVISOR JUNIOR': 'SUPERVISOR JUNIOR',
  'SUPERVISOR JR': 'SUPERVISOR JUNIOR',
  'SUPERVISOR JR.': 'SUPERVISOR JUNIOR',
  'SUP JUNIOR': 'SUPERVISOR JUNIOR',
  'SUP. JUNIOR': 'SUPERVISOR JUNIOR',
  'SUP JR': 'SUPERVISOR JUNIOR',
  'SUP. JR': 'SUPERVISOR JUNIOR',

  // Novas funções
  'ALMOXARIFE': 'ALMOXARIFE',
  'COMERCIAL': 'COMERCIAL',
  'VENDAS': 'COMERCIAL',
  'VENDEDOR': 'COMERCIAL',
  'DIRETOR': 'DIRETOR',
  'DIREÇÃO': 'DIRETOR',
  'DIRECAO': 'DIRETOR',
  'DIRETORIA': 'DIRETOR',
  'DESENVOLVEDOR': 'DESENVOLVEDOR',
  'DEVELOPER': 'DESENVOLVEDOR',
  'DEV': 'DESENVOLVEDOR',
  'GERENTE': 'GERENTE',
  'GESTOR': 'GERENTE',
  'GERENCIA': 'GERENTE',
  'GERÊNCIA': 'GERENTE',
  'MARKETING': 'MARKETING',
  'MKT': 'MARKETING',
  'RH': 'RH',
  'RECURSOS HUMANOS': 'RH',
  'TI': 'TI',
  'TECNOLOGIA DA INFORMACAO': 'TI',
  'TECNOLOGIA DA INFORMAÇÃO': 'TI',
  'INFORMATICA': 'TI',
  'INFORMÁTICA': 'TI',
  'TÉCNICO EM SEGURANÇA DO TRABALHO': 'TÉCNICO EM SEGURANÇA DO TRABALHO',
  'TECNICO EM SEGURANCA DO TRABALHO': 'TÉCNICO EM SEGURANÇA DO TRABALHO',
  'TST': 'TÉCNICO EM SEGURANÇA DO TRABALHO',
  'TECNICO SEGURANCA': 'TÉCNICO EM SEGURANÇA DO TRABALHO',
  'TÉCNICO SEGURANÇA': 'TÉCNICO EM SEGURANÇA DO TRABALHO',
  'TECNICO EM SEGURANCA': 'TÉCNICO EM SEGURANÇA DO TRABALHO',
  'TÉCNICO EM SEGURANÇA': 'TÉCNICO EM SEGURANÇA DO TRABALHO',

  // Serviços Gerais
  'SERVIÇOS GERAIS': 'SERVIÇOS GERAIS',
  'SERVICOS GERAIS': 'SERVIÇOS GERAIS',
  'SG': 'SERVIÇOS GERAIS',
  'S.G.': 'SERVIÇOS GERAIS',
  'SERV GERAIS': 'SERVIÇOS GERAIS',
  'SERV. GERAIS': 'SERVIÇOS GERAIS',

  // Supervisor de Obra
  'SUPERVISOR DE OBRA': 'SUPERVISOR DE OBRA',
  'SUP. OBRA': 'SUPERVISOR DE OBRA',
  'SUP OBRA': 'SUPERVISOR DE OBRA',

  // Supervisor de Segurança
  'SUPERVISOR DE SEGURANÇA': 'SUPERVISOR DE SEGURANÇA',
  'SUPERVISOR SEGURANÇA': 'SUPERVISOR DE SEGURANÇA',
  'SUPERVISOR SEGURANCA': 'SUPERVISOR DE SEGURANÇA',
  'SUPERVISOR DE SEGURANCA': 'SUPERVISOR DE SEGURANÇA',
  'SUP SEGURANÇA': 'SUPERVISOR DE SEGURANÇA',
  'SUP. SEGURANÇA': 'SUPERVISOR DE SEGURANÇA',
  'SUP SEGURANCA': 'SUPERVISOR DE SEGURANÇA',
  'SUP. SEGURANCA': 'SUPERVISOR DE SEGURANÇA',

  // Coordenador
  'COORDENADOR': 'COORDENADOR',
  'COORD': 'COORDENADOR',
  'COORD.': 'COORDENADOR',
  'COODERNADOR': 'COORDENADOR',

  // Eletricista Escalador
  'ELETRICISTA ESCALADOR N1': 'ELETRICISTA ESCALADOR N1',
  'ELETRICISTA N1': 'ELETRICISTA ESCALADOR N1',
  'ELETRICISTA ESCALADOR': 'ELETRICISTA ESCALADOR N1',
  'ELETRICISTA': 'ELETRICISTA ESCALADOR N1',

  // Analista de Planejamento
  'ANALISTA DE PLANEJAMENTO': 'ANALISTA DE PLANEJAMENTO',
  'PLANEJAMENTO': 'ANALISTA DE PLANEJAMENTO',
  'ANALISTA PLANEJAMENTO': 'ANALISTA DE PLANEJAMENTO',

  // Sinônimos extras
  'COLABORADOR': 'MEIO OFICIAL',
  'CONVENCIONAL': 'MEIO OFICIAL',
  'LÍDER': 'COORDENADOR',
  'LIDER': 'COORDENADOR',
  'INSPETOR DE SOLDAGEM': 'INSPETOR DE SOLDA',
  'INSPETOR': 'INSPETOR',
  'INSPETOR SOLDA': 'INSPETOR DE SOLDA',
  'INSPETOR DE SOLDA': 'INSPETOR DE SOLDA',
  'INSPETOR PINTURA': 'INSPETOR DE PINTURA',
  'INSPETOR DE PINTURA': 'INSPETOR DE PINTURA',
  'MOTORISTA': 'MOTORISTA',
  'PINTOR INDUSTRIAL N1': 'PINTOR ESCALADOR N1',
  'PINTOR INDUSTRIAL N2': 'PINTOR ESCALADOR N2',
  'PINTOR INDUSTRIAL N3': 'PINTOR ESCALADOR N3',
  'PINTOR INDUSTRIAL': 'PINTOR CONVENCIONAL',
  'AJUDANTE': 'MEIO OFICIAL',
  'OPERADOR DE MAQUINAS': 'MEIO OFICIAL',
  'OPERADOR DE MÁQUINAS': 'MEIO OFICIAL',
  'OPERADOR DE MÁQUINAS PESADAS': 'MEIO OFICIAL',
  'OPERADOR DE MAQUINAS PESADAS': 'MEIO OFICIAL',
  'N1': 'MEIO OFICIAL',
  'N2': 'MEIO OFICIAL',
  'N3': 'MEIO OFICIAL',
  'NÃO INFORMADO': 'MEIO OFICIAL',
  'NAO INFORMADO': 'MEIO OFICIAL',
};

/**
 * Normaliza uma string de função para a versão padronizada.
 * Retorna a entrada original (em uppercase) se não encontrar match.
 */
export function normalizeFunction(input: string | null | undefined): string {
  if (!input) return '';
  const upper = input.trim().toUpperCase();
  return SYNONYMS[upper] || upper;
}

/**
 * Extrai a função base (categoria) a partir de uma função normalizada.
 * Ex: 'CALDEIREIRO CONVENCIONAL' → 'CALDEIREIRO', 'MECÂNICO ESCALADOR N1' → 'MECÂNICO'
 */
export function getBaseFunction(role: string): string {
  if (!role) return 'MEIO OFICIAL';
  const upper = role.trim().toUpperCase();
  if (upper.startsWith('CALDEIREIRO')) return 'CALDEIREIRO';
  if (upper.startsWith('MECÂNICO') || upper.startsWith('MECANICO')) return 'MECÂNICO';
  if (upper.startsWith('SOLDADOR')) return 'SOLDADOR';
  if (upper.startsWith('PINTOR')) return 'PINTOR';
  if (upper.startsWith('SUPERVISOR DE OBRA')) return 'SUPERVISOR DE OBRA';
  if (upper.startsWith('SUPERVISOR DE SEGURANÇA') || upper.startsWith('SUPERVISOR DE SEGURANCA')) return 'SUPERVISOR DE SEGURANÇA';
  if (upper.startsWith('SUPERVISOR JUNIOR') || upper.startsWith('SUPERVISOR JR')) return 'SUPERVISOR JUNIOR';
  if (upper.startsWith('SUPERVISOR')) return 'SUPERVISOR';
  if (upper === 'MEIO OFICIAL') return 'MEIO OFICIAL';
  if (upper === 'PROGRAMADOR') return 'PROGRAMADOR';
  if (upper === 'PROJETISTA') return 'PROJETISTA';
  if (upper === 'ALMOXARIFE') return 'ALMOXARIFE';
  if (upper === 'COMERCIAL') return 'COMERCIAL';
  if (upper.startsWith('INSPETOR DE PINTURA')) return 'INSPETOR DE PINTURA';
  if (upper.startsWith('INSPETOR DE SOLDA')) return 'INSPETOR DE SOLDA';
  if (upper === 'INSPETOR') return 'INSPETOR';
  if (upper === 'MOTORISTA') return 'MOTORISTA';
  if (upper === 'DESENVOLVEDOR') return 'DESENVOLVEDOR';
  if (upper === 'DIRETOR') return 'DIRETOR';
  if (upper === 'GERENTE') return 'GERENTE';
  if (upper === 'MARKETING') return 'MARKETING';
  if (upper === 'RH') return 'RH';
  if (upper.startsWith('TÉCNICO EM SEGURANÇA') || upper.startsWith('TECNICO EM SEGURANCA')) return 'TÉCNICO EM SEGURANÇA DO TRABALHO';
  if (upper === 'TI') return 'TI';
  if (upper.startsWith('SERVIÇOS GERAIS') || upper.startsWith('SERVICOS GERAIS')) return 'SERVIÇOS GERAIS';
  if (upper.startsWith('COORDENADOR') || upper.startsWith('COORD')) return 'COORDENADOR';
  if (upper.startsWith('ELETRICISTA')) return 'ELETRICISTA ESCALADOR N1';
  if (upper.startsWith('ANALISTA DE PLANEJAMENTO') || upper === 'PLANEJAMENTO') return 'ANALISTA DE PLANEJAMENTO';
  return upper;
}
