// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// NOTE: We intentionally type the client as `any` here because several tables/RPCs
// referenced in the app (project_weekly_progress, backup_schedules, backup_history,
// get_public_branding, get_login_stats, etc.) are not yet reflected in the
// auto-generated `./types` file. Using `any` keeps the build green while runtime
// behavior is preserved.

const SUPABASE_URL = "https://jujzmxbexukxljljpefu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1anpteGJleHVreGxqbGpwZWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyMzUyMTcsImV4cCI6MjA5NTgxMTIxN30.IhfZRgr7Xuex6w7Uz5gNKSV8mcNxYntufOefwiFj4kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});