// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jujzmxbexukxljljpefu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1anpteGJleHVreGxqbGpwZWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyMzUyMTcsImV4cCI6MjA5NTgxMTIxN30.IhfZRgr7Xuex6w7Uz5gNKSV8mcNxYntufOefwiFj4kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});